/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Other/File.java to edit this template
 */
package sdaproject;

import java.util.Scanner;

public class GenerateReport {

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        // Step 1: Login
        System.out.print("Enter Admin Username: ");
        String username = scanner.nextLine();

        System.out.print("Enter Password: ");
        String password = scanner.nextLine();

        if (!username.equals("admin") || !password.equals("1234")) {
            System.out.println("Invalid login. Access denied.");
            return;
        }

        // Step 2: Check if data exists (simulated)
        boolean dataExists = true; // Assume data exists
        if (!dataExists) {
            System.out.println("No data available for the selected criteria.");
            return;
        }

        // Step 3: Select Report Type
        System.out.println("\nSelect Report Type:");
        System.out.println("1. Borrowing Frequency");
        System.out.println("2. Overdue Books");
        System.out.println("3. Catalog Additions");
        System.out.print("Enter your choice (1-3): ");
        int typeChoice = scanner.nextInt();
        scanner.nextLine(); // Clear buffer

        String reportType = switch (typeChoice) {
            case 1 -> "Borrowing Frequency";
            case 2 -> "Overdue Books";
            case 3 -> "Catalog Additions";
            default -> {
                System.out.println("Invalid choice.");
                return ;
            }
        };

        // Step 4: Choose format
        System.out.print("Enter format (PDF or Excel): ");
        String format = scanner.nextLine().toLowerCase();

        if (!(format.equals("pdf") || format.equals("excel"))) {
            System.out.println("Invalid format selected.");
            return;
        }

        // Step 5: Generate and display report
        System.out.println("\nGenerating report...");
        try {
            Thread.sleep(2000); // Simulate delay
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        // Step 6: Show report summary
        System.out.println("\n--- Report Generated ---");
        System.out.println("Report Type: " + reportType);
        System.out.println("Format: " + format.toUpperCase());
        System.out.println("Generated By: " + username);
        System.out.println("Status: Ready for Download");

        scanner.close();
    }
}

